version: '3.1'
services:
  elasticsearch:
   container_name: elasticsearch
   image: elasticsearch:${ELK_VERSION}
   env_file:
      - elasticsearch.env
   ports:
    - 9200:9200
   volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
   networks:
    - elastic

  kibana:
   container_name: kibana
   image: kibana:${ELK_VERSION}
   env_file:
      - kibana.env
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   networks:
    - elastic
  
networks:
  elastic:
    driver: bridge