CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE SEQUENCE "Book_AuthorId_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE SEQUENCE "Book_Id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE SEQUENCE "Book_PublisherId_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE SEQUENCE "Publisher_Id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE TABLE "Author" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        CONSTRAINT "Author_pkey" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE TABLE "Publisher" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PublisherName" character varying(100) NOT NULL,
        "Address" character varying(100) NOT NULL,
        CONSTRAINT "Publisher_pkey" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE TABLE "Book" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(100) NOT NULL,
        "AuthorId" integer NOT NULL,
        "PageCount" integer NULL,
        "Price" integer NULL,
        "PublisherId" integer NOT NULL,
        CONSTRAINT "Book_pkey" PRIMARY KEY ("Id"),
        CONSTRAINT "Book_AuthorId_fkey" FOREIGN KEY ("AuthorId") REFERENCES "Author" ("Id"),
        CONSTRAINT "Book_PublisherId_fkey" FOREIGN KEY ("PublisherId") REFERENCES "Publisher" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE INDEX "IX_Book_AuthorId" ON "Book" ("AuthorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    CREATE INDEX "IX_Book_PublisherId" ON "Book" ("PublisherId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129161646_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240129161646_InitialCreate', '7.0.15');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129163731_AddBookFieldPrinting') THEN
    ALTER TABLE "Book" ADD "Printing" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240129163731_AddBookFieldPrinting') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240129163731_AddBookFieldPrinting', '7.0.15');
    END IF;
END $EF$;
COMMIT;

